sudo: false
language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19
before_script:
  - mix local.hex --force
  - mix deps.get --only test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
env:
  - MIX_ENV=test
script: mix coveralls.travis
