language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0
env:
  - MIX_ENV=test
before_script:
  - mix local.hex --force
  - mix deps.get --only test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
# script: mix coveralls.travis
script: mix test
